@echo Updating submodules...
@git submodule update --init --recursive

@echo Building project...
if not exist "build" mkdir build
@cd build
@echo Removing everything in build...
@rd /s /q *
@echo Building project...
@cmake ..

@echo Done building project.