version: '3'
services:
  server:
    image: ubuntu:latest
    volumes:
      - .:/app
    working_dir: /app/
    command: bash -c "apt-get update && apt-get install -y g++ cmake libboost-all-dev libconfig++-dev && ./buildserver.sh && LD_LIBRARY_PATH=/usr/local/lib:/usr/lib/x86_64-linux-gnu ./r-type_server 4248 test.cfg"
    ports:
      - 4248:4248
    networks:
      - mynet
networks:
  mynet:
    driver: bridge