version: '3'
services:
  server:
    image: gcc:latest
    volumes:
      - .:/app
    working_dir: /app/
    command: bash -c "apt-get update && apt-get install -y cmake libboost-dev && ./build.sh"
    ports:
      - 4000:4000
    networks:
      - mynet
networks:
  mynet:
    driver: bridge