version: '3'
services:
  server:
    image: gcc:latest
    volumes:
      - .:/app
      - ./build:/app/build
    working_dir: /app
    command: bash -c "apt-get update && apt-get install -y cmake libboost-dev && mkdir -p build && cd build && cmake .. && make && ./r-type_server 127.0.0.1 4000"
    ports:
      - 4000:4000
    networks:
      - mynet
networks:
  mynet:
    driver: bridge