name: Build and Release

on:
    push:
        branches:
        - networking
    pull_request:
        branches:
        - networking

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: sudo apt-get update && sudo apt-get install -y libboost-dev cmake
        - name: Build & Package
          run: mkdir build/ && cd build/ && cmake .. && make && cpack -G DEB
        - name: Upload the package
          uses: actions/upload-artifact@v2
          with:
              name: rtype-server
              path: build/*.deb
    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Download the package
          uses: actions/download-artifact@v2
          with:
              name: rtype-server
              path: build/
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
              files: build/*.deb
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
