name: Build and Test

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            submodules: false
        - name: Update submodules
          run: |
            git submodule deinit -f .
            git submodule update --init --recursive
        - name: Install cmake
          run: |
            sudo apt-get update
            sudo apt-get install -y cmake
        - name: Build
          run: mkdir build/ && cd build/ && cmake .. && make
