name: Check Build standalone Server

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        container: 
            image: ubuntu:latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                apt-get update
                apt-get install -y libboost-all-dev
                apt-get install -y libconfig++-dev
                apt-get install -y make
                apt-get install -y g++
            - name: Build
              run: |
                make