name: Check Build standalone Server

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: self-hosted
        container: 
            image: ubuntu:latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                apt-get update
                apt-get install -y make
                apt-get install -y g++
                apt-get install -y cmake
                apt-get install -y git
                apt-get install -y libsfml-dev
                apt-get install -y libx11-dev
                apt-get install -y libudev-dev          
            - name: Build
              run: |
                bash build.sh