name: Build Client

on:
    push:
        branches:
        - client
    pull_request:
        branches:
        - client

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            submodules: false
        - name: Update submodules
          run: |
            git submodule deinit -f .
            git submodule update --init --recursive
        - name: Install dependencies
          run: |
            sudo apt update
            sudo apt install -y \
                libsfml-dev
                cmake
            - name: Build
              run: |
                mkdir build
                cd build
                cmake ..
                make
                