name: Build Client

on:
    push:
        branches:
        - client
    pull_request:
        branches:
        - client

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ~/.apt/cache
            key: ${{ runner.os }}-apt-${{ hashFiles('**/client_build.yml') }}
            restore-keys: |
              ${{ runner.os }}-apt-
        - name: Install dependencies
          run: |
            sudo apt update
            sudo apt install -y \
                build-essential \
                libsfml-dev \
                libboost-all-dev \
                cmake \
                g++
        - name: Set up compilers
          run: |
            echo "CC=/usr/bin/gcc" >> $GITHUB_ENV
            echo "CXX=/usr/bin/g++" >> $GITHUB_ENV
        - name: Verify compilers
          run: |
            which gcc
            which g++
        - name: Build
          run: |
            mkdir build
            cd build
            cmake ..
            make
                