name: Docker-Compose for Server

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
              with:
                  driver: docker-container
                  install: true
            - name: Start Docker daemon
              run: |
                  service docker start
            - name: Verify Docker daemon
              run: |
                  docker info
            - name: Runs docker-compose
              run: |
                  apt-get update
                  apt-get install -y docker-compose
                  docker-compose up -d
